version: '2'
services:
    app_2048:
        build: .
        ports:
            - "80"
        links:
            - redis
        restart: unless-stopped

    redis:
        image: redis
        expose:
            - "6379"
        restart: unless-stopped

stage34:
    entry: app_2048
